"""ISO document structure from the PDF text layer (PyMuPDF), without models.

ISO standards follow ISO/IEC Directives Part 2: numbered clauses ("4.2.4"),
annexes ("Annex A", "A.1"), captions ("Table 2 —", "Figure 1 —") and numbered
equations ("(1)" at the right margin). These rules are deterministic, so the
structure is recovered from line text, font weight and geometry:

* clause numbers must advance plausibly (figure keys "1 Datum line" and table of
  contents entries are therefore never taken for clauses);
* a clause number and its title on the same baseline are merged;
* inline symbols set as separate glyph runs ("α" + subscript "yt") are joined
  back into their text line (``merge_inline_fragments``);
* repeated page headers/footers are learned per document (``repeated_furniture``);
* tables use PyMuPDF's cell grid, filled with the cleaned text lines; bold leading
  rows are header rows; "(continued)" captions, unit notes and footnotes are kept;
* equation regions are anchored on the right-margin equation number, bounded by
  the surrounding prose, and rebuilt from glyph geometry (``parsing/formula.py``);
* "where" legends and figure keys become their own blocks.
Nothing is generated by a model; formula text that cannot be explained by the
page geometry is marked ``needs_review`` and never turned into LaTeX.
"""
from __future__ import annotations

import math
import re
from collections import Counter
from dataclasses import dataclass, field

import pymupdf

from app.ingestion.extractors.base import Block, normalize_hyphens
from app.ingestion.parsing import formula as F
from app.ingestion.parsing.symbols import map_symbol_span

_UNICODE_SPACES = re.compile(r"[  -​  　﻿]")
_CONTROL = re.compile(r"[\x00-\x08\x0b-\x1f\x7f]")  # BSI footers end in a backspace (\x08)
CLAUSE_NUM = re.compile(r"^(\d{1,2}(?:\.\d{1,2}){0,5}|[A-Z](?:\.\d{1,2}){1,5})$")
CLAUSE_LINE = re.compile(r"^(\d{1,2}(?:\.\d{1,2}){0,5}|[A-Z](?:\.\d{1,2}){1,5})\s+(\S.*)$")
ANNEX = re.compile(r"^Annex\s+([A-Z])\b\s*(.*)$")
ANNEX_TYPE = re.compile(r"^\((?:informative|normative)\)$")
TOC_LEADER = re.compile(r"\.{5,}\s*\S{0,6}\s*$")
TABLE_CAP = re.compile(r"^Table\s+((?:[A-Z]\.)?\d{1,3})\s*[—–-]\s*\S")
TABLE_CONT = re.compile(r"^Table\s+((?:[A-Z]\.)?\d{1,3})\s*\((?:continued|concluded)\)", re.IGNORECASE)
FIG_CAP = re.compile(r"^Figure\s+((?:[A-Z]\.)?\d{1,3})\s*[—–-]\s*\S")
EQ_NUM = re.compile(r"^\(((?:[A-Z]\.)?\d{1,3}[a-z]?)\)$")
NOTE = re.compile(r"^(?:NOTE(?:\s+\d+)?\b|Note\s+\d+\s+to\s+entry)")
EXAMPLE = re.compile(r"^EXAMPLE(?:\s+\d+)?\b")
LIST_ITEM = re.compile(r"^(?:[—–•\-]\s|[a-z]\)\s)")
WHERE = re.compile(r"^where\s*:?$", re.IGNORECASE)
WHERE_INLINE = re.compile(r"^where\s+(\S{1,12})\s+(?:is|are|designates|denotes|=)\s", re.IGNORECASE)
UNIT_NOTE = re.compile(r"^(?:Dimensions|Deviations|Values|Tolerances|Measurements)\s+in\s+\S+", re.IGNORECASE)
UNIT_TOKEN = re.compile(r"(?<![\w/])(mm|µm|μm|m|cm|degrees?|°|rad|N|kN|N/mm2|N/mm²|MPa|GPa|%|s|min|kg|Nm|N·m|"
                        r"in millimetres|in micrometres|in degrees)(?![\w/])")
UNNUMBERED = {"foreword", "introduction", "contents", "bibliography", "index"}
FURNITURE = [
    re.compile(r"^(?:(?:BS\s+)?(?:EN\s+)?(?:ISO|ISO/TR|ISO/TS)\s?\d{2,5}(?:-\d+)?:\d{4}(?:\(E\))?)$"),
    # "© ISO 2017 – All rights reserved", also with the page number set on the same line ("12 © ISO …")
    re.compile(r"^(?:\d{1,3}\s+)?©\s*ISO(?:\s+\d{4})?(?:\s*[–-]\s*All rights reserved)?(?:\s+\d{1,3})?$",
               re.IGNORECASE),
    re.compile(r"^(?:INTERNATIONAL STANDARD|TECHNICAL REPORT)(?:\s+©\s*ISO)?$"),
    re.compile(r"^[ivxlc]{1,6}$|^\d{1,3}$", re.IGNORECASE),
    re.compile(r"^--`[`,\-]*---$"),
    re.compile(r"^www\.bzfxw\.com$"),
    re.compile(r"^(Copyright International Organization for Standardization|Provided by IHS under license with ISO"
               r"|No reproduction or networking permitted without license from IHS|Not for Resale"
               r"|Licensee=.*|.*Not for Resale.*)$"),
]
# repeated-furniture learning: bands measured on the corpus (headers at 3-10 % of the page height,
# footers/page numbers at 93-96 %); repeated table headers of ISO 286-2 start at 12 % and stay content
HEADER_BAND = 0.11
FOOTER_BAND = 0.89
REPEAT_SHARE = 0.3
EQ_WINDOW = 45.0  # pt above/below the equation number searched for its glyphs (tallest ISO 21771 formulas ~80 pt)


@dataclass(eq=False)
class Seg:
    """One span of a line: its position, size and baseline drive inline-symbol and formula reconstruction."""

    text: str
    bbox: tuple[float, float, float, float]
    size: float
    baseline: float
    font: str = ""
    bold: bool = False


@dataclass(eq=False)
class Line:
    text: str
    bbox: tuple[float, float, float, float]
    bold: bool = False
    horizontal: bool = True
    used: bool = False
    size: float = 10.0
    segs: list[Seg] = field(default_factory=list)
    absorbed: bool = False  # merged into another line (inline symbol / subscript)

    @property
    def yc(self) -> float:
        return (self.bbox[1] + self.bbox[3]) / 2

    @property
    def height(self) -> float:
        return max(0.1, self.bbox[3] - self.bbox[1])

    # vertical extent from glyph baselines and font size: some PDFs (BSI prints) report line boxes that are
    # several text lines tall, which would merge rows and cut equation bands
    @property
    def vtop(self) -> float:
        return min((sg.baseline - 0.78 * sg.size for sg in self.segs), default=self.bbox[1])

    @property
    def vbottom(self) -> float:
        return max((sg.baseline + 0.22 * sg.size for sg in self.segs), default=self.bbox[3])

    @property
    def vc(self) -> float:
        return (self.vtop + self.vbottom) / 2

    @property
    def vheight(self) -> float:
        return max(0.1, self.vbottom - self.vtop)


@dataclass
class LayoutState:
    """Carried across pages: the last accepted clause number and the learned page furniture."""

    clause_key: tuple = ()
    in_key: bool = False
    repeated: set[str] = field(default_factory=set)
    stats: dict = field(default_factory=lambda: {"symbol_glyphs_mapped": 0, "rotated_lines": 0,
                                                 "unmapped_symbol_fonts": set(), "inline_merges": 0,
                                                 "repeated_furniture_lines": 0, "formulas": 0,
                                                 "formulas_needs_review": 0, "tables_grid": 0, "tables_lines": 0,
                                                 "legends": 0, "figures": 0})


def _clean(s: str) -> str:
    # soft hyphens (U+00AD) stay: a line-final one joins the next line only after the lines of a
    # page or paragraph are joined (normalize_hyphens), exactly as the page text layer does
    s = s.replace("‐", "-").replace("‑", "-").replace("‒", "-")
    return _UNICODE_SPACES.sub(" ", _CONTROL.sub("", s)).strip()


def page_lines(page: "pymupdf.Page", state: LayoutState) -> list[Line]:
    """Text lines with Symbol-encoded Greek recovered (reading order of PyMuPDF), with span geometry."""
    out: list[Line] = []
    # rawdict: per-character origins and boxes. A span's own origin can belong to a synthesized
    # leading space set on the previous glyph's baseline, which would misplace sub-/superscripts.
    d = page.get_text("rawdict", flags=pymupdf.TEXTFLAGS_TEXT)
    for b in d.get("blocks", []):
        for ln in b.get("lines", []):
            parts, bold_chars, chars, segs, sizes = [], 0, 0, [], Counter()
            for sp in ln.get("spans", []):
                glyphs = sp.get("chars", [])
                raw = "".join(g["c"] for g in glyphs) if glyphs else sp.get("text", "")
                text, n = map_symbol_span(sp.get("font", ""), raw)
                if n:
                    state.stats["symbol_glyphs_mapped"] += n
                    state.stats["unmapped_symbol_fonts"].add(sp.get("font", ""))
                parts.append(text)
                visible = len(text.strip())
                chars += visible
                bold = bool(sp.get("flags", 0) & 16 or "bold" in sp.get("font", "").lower())
                if bold:
                    bold_chars += visible
                if visible:
                    size = round(float(sp.get("size", 10.0)), 1)
                    sizes[size] += visible
                    ink = [g for g in glyphs if not g["c"].isspace()]
                    box = (min(g["bbox"][0] for g in ink), min(g["bbox"][1] for g in ink),
                           max(g["bbox"][2] for g in ink), max(g["bbox"][3] for g in ink)) if ink else tuple(sp["bbox"])
                    base = float(ink[0]["origin"][1]) if ink else float(sp.get("origin", (0, sp["bbox"][3]))[1])
                    segs.append(Seg(_CONTROL.sub("", text).strip(), box, size, base, sp.get("font", ""), bold))
            text = _clean("".join(parts))
            if not text:
                continue
            dx, dy = ln.get("dir", (1, 0))
            horizontal = abs(dy) < 0.1 and dx > 0
            if not horizontal:
                state.stats["rotated_lines"] += 1
            out.append(Line(text, tuple(ln["bbox"]), bold=chars > 0 and bold_chars / chars > 0.6,
                            horizontal=horizontal, size=sizes.most_common(1)[0][0] if sizes else 10.0, segs=segs))
    return out


def page_text(lines: list[Line]) -> str:
    return "\n".join(ln.text for ln in lines if not ln.absorbed)


# --------------------------------------------------------------------------- page furniture
def furniture_key(text: str) -> str:
    return re.sub(r"\d+", "#", re.sub(r"\s+", " ", _clean(text).lower()))


_NEVER_FURNITURE = [TABLE_CAP, TABLE_CONT, FIG_CAP, CLAUSE_LINE, UNIT_NOTE, NOTE, EQ_NUM]


def repeated_furniture(pages: list[tuple[float, list[Line]]]) -> set[str]:
    """Running headers/footers of one document: short lines in the header/footer band that recur at the
    same place on at least 30 % of the pages (min. 3). Captions, clause lines and unit notes never qualify."""
    counts: Counter = Counter()
    for height, lines in pages:
        seen = set()
        for ln in lines:
            t = ln.text.strip()
            if not ln.horizontal or not t or len(t) > 90 or any(p.match(t) for p in _NEVER_FURNITURE[:-1]):
                continue
            if ln.bbox[3] <= HEADER_BAND * height or ln.bbox[1] >= FOOTER_BAND * height:
                seen.add((furniture_key(t), round(ln.bbox[1] / height, 2)))
        counts.update(seen)
    need = max(3, math.ceil(REPEAT_SHARE * len(pages)))
    by_key: Counter = Counter()
    for (key, _y), c in counts.items():
        by_key[key] = max(by_key[key], c)
    # a key is page furniture only when it is text (>= 3 letters) or a bare page number: single glyphs of
    # glyph-positioned PDFs ("a", "(") recur everywhere and are never furniture
    return {k for k, c in by_key.items()
            if c >= need and (k == "#" or len(re.findall(r"[^\W\d_]", k)) >= 3)}


def _is_furniture(ln: Line, height: float, state: LayoutState | None = None) -> bool:
    t = ln.text.strip()
    if any(p.match(t) for p in FURNITURE[4:]):
        return True
    in_margin = ln.bbox[3] < 0.085 * height or ln.bbox[1] > 0.915 * height
    if in_margin and len(t) < 70 and any(p.match(t) for p in FURNITURE):
        return True
    if state is not None and state.repeated and (ln.bbox[3] <= HEADER_BAND * height or ln.bbox[1] >= FOOTER_BAND * height):
        return furniture_key(t) in state.repeated
    return False


# --------------------------------------------------------------------------- prose / structure tests
_MATH_WORDS = {"cos", "sin", "tan", "cot", "inv", "max", "min", "exp", "log", "arc", "arccos", "arcsin", "arctan"}


def _is_prose(t: str) -> bool:
    words = [w for w in re.findall(r"[a-z]{3,}", t) if w not in _MATH_WORDS]
    return len(t) >= 25 and len(words) >= 4


def _is_text_label(ln: "Line | str") -> bool:
    r"""Words next to an equation that are not part of it: "Transverse base pitch:", "(See Figure 12.)",
    "Equations (5) to (7):", "For spur gears, β = 0°". Only full-size glyph runs count (subscripts such as
    "bn.amax" are not words), and all-capital operators ("INT") or unit words ("in radians") are not text."""
    t = ln if isinstance(ln, str) else ln.text
    if re.match(r"^\(?See\s", t) or re.match(r"^(?:Equations?|Formulae?)\s", t):
        return True
    segs = [] if isinstance(ln, str) else ln.segs
    big = max((sg.size for sg in segs), default=0.0)
    full = " ".join(sg.text for sg in segs if sg.size >= 0.9 * big) if segs else t
    words = [w for w in re.findall(r"[A-Za-z]{3,}", full)
             if w.lower() not in _MATH_WORDS and not w.isupper() and re.search(r"[aeiouy]", w.lower())]
    if t.rstrip().endswith(":") and words:
        return True
    return len(words) >= 2 and not re.fullmatch(r"(?:in\s+)?(?:radians|degrees|mm|µm)", t.strip())


_STRUCTURAL_WORDS = {"Key", "where", "NOTE"}


def _is_structural(ln: Line) -> bool:
    """Headings, captions and legend markers are never glyphs of a neighbouring equation."""
    t = ln.text
    return (t in _STRUCTURAL_WORDS or bool(WHERE.match(t) or TABLE_CAP.match(t) or TABLE_CONT.match(t)
                                            or FIG_CAP.match(t) or ANNEX.match(t) or NOTE.match(t))
            or bool(CLAUSE_LINE.match(t) and ln.bold) or bool(CLAUSE_NUM.match(t) and ln.bold))


# --------------------------------------------------------------------------- inline symbols
def _v_overlap(a: Line, b: Line) -> float:
    return max(0.0, min(a.vbottom, b.vbottom) - max(a.vtop, b.vtop)) / min(a.vheight, b.vheight)


def _is_script(frag: Line, host: Line) -> bool:
    fb = frag.segs[0].baseline if frag.segs else frag.bbox[3]
    hb = min((s.baseline for s in host.segs), default=host.bbox[3], key=lambda b: abs(b - fb))
    return frag.size < 0.86 * host.size and abs(fb - hb) > 0.1 * host.size


def merge_inline_fragments(page: "pymupdf.Page", lines: list[Line], state: LayoutState,
                           table_boxes: list[tuple] | None = None) -> list[Line]:
    """Join glyph runs that PyMuPDF put on their own line although they sit on a text row: a Greek symbol
    and its subscript ("α" + "yt" -> "αyt"), a symbol inside a sentence ("the base diameter, db, is given
    by"). Only horizontally adjacent runs of the same visual row merge; inside tables only touching runs
    (subscripts), so table cells never fuse. Returns the lines that remain (absorbed ones are dropped)."""
    height = page.rect.height
    boxes = table_boxes or []
    live = [ln for ln in lines if ln.horizontal and not ln.absorbed and not _is_furniture(ln, height, state)
            and not EQ_NUM.match(ln.text)]
    in_table = {id(ln): any(_inside(ln, b) for b in boxes) for ln in live}
    # row buckets (4 pt) keep this linear on pages with thousands of glyph runs
    buckets: dict[int, list[Line]] = {}
    for ln in live:
        for k in range(int(ln.vtop // 4), int(ln.vbottom // 4) + 1):
            buckets.setdefault(k, []).append(ln)
    for f in sorted(live, key=lambda ln: ln.bbox[0]):
        if f.absorbed or len(f.text) > 40:
            continue
        tol = (0.35 if in_table[id(f)] else 1.5) * max(f.size, 6.0)
        best, best_key = None, None
        near = {id(h): h for k in range(int(f.vtop // 4), int(f.vbottom // 4) + 1) for h in buckets.get(k, [])}
        for h in near.values():
            if h is f or h.absorbed or in_table[id(h)] != in_table[id(f)] or _v_overlap(f, h) < 0.5:
                continue
            gap_after = f.bbox[0] - h.bbox[2]
            gap_before = h.bbox[0] - f.bbox[2]
            inside = h.bbox[0] < (f.bbox[0] + f.bbox[2]) / 2 < h.bbox[2]
            if -1.0 <= gap_after <= tol:
                key = (0, gap_after)
            elif -1.0 <= gap_before <= tol and len(h.text) > len(f.text):
                key = (1, gap_before)
            elif inside and not in_table[id(f)] and not any(s.bbox[0] < f.bbox[2] - 0.5 and f.bbox[0] + 0.5 < s.bbox[2]
                                                           for s in h.segs):
                key = (2, 0.0)
            else:
                continue
            key = (key[0], -_v_overlap(f, h), key[1])
            if best_key is None or key < best_key:
                best, best_key = h, key
        if best is not None:
            _absorb(best, f)
            state.stats["inline_merges"] += 1
    return [ln for ln in lines if not ln.absorbed]


def _absorb(host: Line, frag: Line) -> None:
    """Insert ``frag`` into ``host`` at its x position (segment order); scripts join without a space."""
    script = _is_script(frag, host)
    segs = sorted(host.segs + frag.segs, key=lambda s: s.bbox[0])
    # rebuild the text: original spans of the host keep their own spacing, a space is added at a visible gap
    out, prev = "", None
    for s in segs:
        if prev is not None:
            gap = s.bbox[0] - prev.bbox[2]
            joined_script = script and (s in frag.segs or prev in frag.segs) and gap < 0.5 * host.size
            if not joined_script and gap > 0.22 * host.size and not out.endswith(" ") and not s.text.startswith(" "):
                out += " "
        out += s.text
        prev = s
    host.text = _clean(re.sub(r" {2,}", " ", out))
    host.segs = segs
    host.bbox = (min(host.bbox[0], frag.bbox[0]), min(host.bbox[1], frag.bbox[1]),
                 max(host.bbox[2], frag.bbox[2]), max(host.bbox[3], frag.bbox[3]))
    host.bold = host.bold and frag.bold if len(frag.text) > 3 else host.bold
    frag.absorbed = True
    frag.used = True


def _merge_baseline_numbers(lines: list[Line], table_boxes: list[tuple] | None = None) -> None:
    """'4.2.4' and its title set as separate text lines on one baseline -> one line. Never inside a table:
    a cell "3" next to a cell "6" is a row of values, not a clause number and its title."""
    for ln in lines:
        if ln.used or not CLAUSE_NUM.match(ln.text) and not ANNEX.match(ln.text):
            continue
        if table_boxes and any(_inside(ln, b) for b in table_boxes):
            continue
        for other in lines:
            if other is ln or other.used or not other.horizontal:
                continue
            if abs(other.yc - ln.yc) <= 2.5 and 0 < other.bbox[0] - ln.bbox[2] < 120:
                ln.text = f"{ln.text} {other.text}"
                ln.bold = ln.bold or other.bold
                ln.bbox = (ln.bbox[0], min(ln.bbox[1], other.bbox[1]), other.bbox[2], max(ln.bbox[3], other.bbox[3]))
                ln.segs = ln.segs + other.segs
                other.used = True
                break


# --------------------------------------------------------------------------- clauses
def clause_key(num: str) -> tuple:
    parts = num.split(".")
    if parts[0].isalpha():
        return (100 + ord(parts[0]) - ord("A"),) + tuple(int(p) for p in parts[1:])
    return tuple(int(p) for p in parts)


def plausible_next(cur: tuple, cand: tuple, strong: bool = False) -> bool:
    """ISO numbering advances by one step (a skipped number is tolerated). ``strong`` evidence (a bold
    numbered heading with a title) may skip further, so one missed heading does not cascade."""
    if not cand or cand <= cur:
        return False
    step = 5 if strong else 2
    if cand[0] >= 100:  # annexes follow the body or the previous annex
        prev = cur[0] if cur and cur[0] >= 100 else 99
        if cand[0] not in (prev, prev + 1, prev + 2):
            return False
        cur = cur if cur and cur[0] == cand[0] else (cand[0],)
        if cand == cur:
            return True
    elif not cur:
        return (cand[0] in (0, 1) or strong and cand[0] <= step) and all(p <= 2 for p in cand[1:])
    for i, (a, b) in enumerate(zip(cur, cand)):
        if a != b:
            return 0 < b - a <= step and all(p <= 2 for p in cand[i + 1:])
    return len(cand) == len(cur) + 1 and 1 <= cand[-1] <= (step if strong else 2)  # first sub-clause


# --------------------------------------------------------------------------- tables
@dataclass
class TableGrid:
    bbox: tuple[float, float, float, float]
    rows: list[list[tuple | None]]  # cell boxes per row (None = covered by a merged cell)


def page_tables(page: "pymupdf.Page") -> list[TableGrid]:
    try:
        found = page.find_tables().tables
    except Exception:  # pragma: no cover - table finder is best-effort
        return []
    out = []
    for t in found:
        try:
            rows = [[tuple(c) if c else None for c in r.cells] for r in t.rows]
        except Exception:  # pragma: no cover
            rows = []
        out.append(TableGrid(tuple(t.bbox), rows))
    return out


def _table_boxes(page: "pymupdf.Page") -> list[tuple[float, float, float, float]]:
    return [t.bbox for t in page_tables(page)]


def _inside(ln: Line, box) -> bool:
    x = (ln.bbox[0] + ln.bbox[2]) / 2
    return box[0] - 2 <= x <= box[2] + 2 and box[1] - 2 <= ln.yc <= box[3] + 2


def rows_from_lines(lines: list[Line]) -> list[list[str]]:
    """Group table lines into rows (vertical overlap), cells ordered left to right."""
    rows: list[list[Line]] = []
    for ln in sorted(lines, key=lambda l_: (l_.yc, l_.bbox[0])):
        if rows:
            top = min(x.bbox[1] for x in rows[-1])
            bottom = max(x.bbox[3] for x in rows[-1])
            if ln.yc < bottom - 1 and ln.yc > top:
                rows[-1].append(ln)
                continue
        rows.append([ln])
    return [[c.text for c in sorted(r, key=lambda l_: l_.bbox[0])] for r in rows]


_NUMERIC_CELL = re.compile(r"^[+−\-±]?\s?\d[\d\s]*(?:[.,]\d+)?$|^[—–-]$")


def _cell_text(lines: list[Line]) -> str:
    parts = [ln.text for ln in sorted(lines, key=lambda l_: (round(l_.yc), l_.bbox[0]))]
    if len(parts) >= 2 and all(_NUMERIC_CELL.match(p.strip()) for p in parts):
        return " / ".join(parts)  # stacked limits (upper / lower deviation) of one cell
    return " ".join(parts)


def grid_rows(grid: TableGrid, members: list[Line]) -> tuple[list[list[str]], list[list[bool]], float]:
    """Fill the finder's cell grid with the cleaned lines. Returns cell texts, per-cell bold flags and the
    share of member lines that found no cell."""
    cells: list[list[list[Line]]] = [[[] for _ in r] for r in grid.rows]
    lost = 0
    for ln in members:
        x, y = (ln.bbox[0] + ln.bbox[2]) / 2, ln.yc
        hit = None
        for ri, r in enumerate(grid.rows):
            for ci, c in enumerate(r):
                if c and c[0] - 1 <= x <= c[2] + 1 and c[1] - 1 <= y <= c[3] + 1:
                    hit = (ri, ci)
                    break
            if hit:
                break
        if hit is None:
            lost += 1
            continue
        cells[hit[0]][hit[1]].append(ln)
    texts = [[_cell_text(c) if grid.rows[ri][ci] else "" for ci, c in enumerate(r)] for ri, r in enumerate(cells)]
    bold = [[bool(c) and all(ln.bold for ln in c) for c in r] for r in cells]
    keep = [i for i, r in enumerate(texts) if any(t.strip() for t in r)]
    return [texts[i] for i in keep], [bold[i] for i in keep], (lost / len(members) if members else 0.0)


def header_row_count(rows: list[list[str]], bold: list[list[bool]] | None) -> int:
    """Leading rows set in bold (>= half of their non-empty cells) are header rows (max. 3). Without font
    evidence the first row is a header when it holds no numeric cell."""
    n = 0
    if bold:
        for r, b in zip(rows[:3], bold[:3]):
            filled = [bb for t, bb in zip(r, b) if t.strip()]
            if filled and sum(filled) / len(filled) >= 0.5:
                n += 1
            else:
                break
    if n == 0 and len(rows) >= 2 and rows[0] and not any(_NUMERIC_CELL.match(c.strip()) for c in rows[0] if c.strip()):
        n = 1
    return min(n, max(0, len(rows) - 1))


def column_names(rows: list[list[str]], header_rows: int) -> list[str]:
    """One name per column from the header rows; a merged header cell names every column it spans."""
    if not header_rows or not rows:
        return []
    width = max(len(r) for r in rows)
    names = [""] * width
    for r in rows[:header_rows]:
        cur = ""
        for ci in range(width):
            cell = r[ci].strip() if ci < len(r) else ""
            cur = cell or cur  # fill forward across merged cells
            if cur and cur not in names[ci]:
                names[ci] = f"{names[ci]} / {cur}".strip(" /")
    return names


def render_table(caption: str | None, rows: list[list[str]], header_rows: int = 0) -> str:
    lines = []
    for i, r in enumerate(rows):
        if not any(c.strip() for c in r):
            continue
        lines.append("| " + " | ".join(r) + " |")
        if header_rows and i == header_rows - 1:
            lines.append("|" + " --- |" * len(r))
    body = "\n".join(lines)
    return f"{caption}\n{body}" if caption else body


def table_units(texts: list[str]) -> list[str]:
    out: list[str] = []
    for t in texts:
        for m in UNIT_TOKEN.finditer(t):
            u = m.group(1).replace("μ", "µ")
            u = {"in millimetres": "mm", "in micrometres": "µm", "in degrees": "°", "degree": "°", "degrees": "°"}.get(u, u)
            if u not in out:
                out.append(u)
    return out


def linearize(fragments: list[Line]) -> str:
    """Positioned formula glyph runs in left-to-right order. A run that directly touches the previous
    one and is set smaller (a subscript: "m" + "n") is joined without a space ("mn"). Only the PDF's
    own characters are used; fractions are NOT reconstructed (the order stays approximate)."""
    out, prev = "", None
    for ln in sorted(fragments, key=lambda l_: (round(l_.bbox[0] / 4), l_.yc)):
        if prev is not None:
            h_prev, h = prev.bbox[3] - prev.bbox[1], ln.bbox[3] - ln.bbox[1]
            touching = -1.0 <= ln.bbox[0] - prev.bbox[2] <= 1.5
            out += "" if touching and h < 0.85 * h_prev else " "
        out += ln.text
        prev = ln
    return out


# --------------------------------------------------------------------------- legends / keys
_LEGEND_VAR = re.compile(r"^(?P<sym>[^\s,;]{1,12})\s+(?:is|are|designates|denotes|represents|=|—|–)\s+"
                         r"(?:the\s+|a\s+|an\s+)?(?P<desc>.+?)\s*[;.]?$")
_UNIT_TAIL = re.compile(r",\s*(?:in\s+)?(?P<unit>mm|µm|μm|m|degrees?|°|rad|N|kN|N/mm2|MPa|%|s|min|kg|Nm)\s*$")


def parse_variable(text: str) -> dict | None:
    m = _LEGEND_VAR.match(text.strip())
    if not m:
        return None
    desc, unit = m.group("desc").strip(), None
    mu = _UNIT_TAIL.search(desc)
    if mu:
        unit = mu.group("unit").replace("μ", "µ")
        desc = desc[: mu.start()].strip()
    return {"symbol": m.group("sym"), "description": desc.rstrip(";,."), "unit": unit}


def _visual_rows(lines: list[Line]) -> list[list[Line]]:
    rows: list[list[Line]] = []
    for ln in sorted(lines, key=lambda l_: (l_.yc, l_.bbox[0])):
        if rows and any(_v_overlap(ln, o) >= 0.5 for o in rows[-1]):
            rows[-1].append(ln)
        else:
            rows.append([ln])
    return [sorted(r, key=lambda l_: l_.bbox[0]) for r in rows]


def _legend(where: Line, live: list[Line]) -> tuple[list[Line], list[dict]]:
    """Rows after a "where" marker that define symbols ("d is the reference diameter, mm;")."""
    below = [ln for ln in live if not ln.used and ln is not where and ln.yc > where.yc - 1
             and not EQ_NUM.match(ln.text)]
    taken: list[Line] = []
    variables: list[dict] = []
    last_bottom = where.bbox[3]
    for row in _visual_rows(below)[:40]:
        top = min(ln.bbox[1] for ln in row)
        if top - last_bottom > 2.2 * max(where.height, 8):
            break
        text = " ".join(ln.text for ln in row)
        if any(_is_structural(ln) for ln in row) or TABLE_CAP.match(text) or FIG_CAP.match(text):
            break
        var = parse_variable(text)
        if var is None and variables and text[:1].islower() and not re.match(r"^\S{1,8}\s+(?:is|are)\b", text):
            variables[-1]["description"] += " " + text.rstrip(";.")  # wrapped description
        elif var is None:
            break
        else:
            variables.append(var)
        taken += row
        last_bottom = max(ln.bbox[3] for ln in row)
    return taken, variables


# figure key items: "1 Datum line", "a tooth flank", "hFfP straight portion" (never an ordinary sentence)
_KEY_ITEM = re.compile(r"^(?!(?:The|This|For|All|An?|In|It|If|Of|On|See|At)\s)(?:\d{1,2}[a-z]?|[A-Za-z]|"
                       r"[A-Za-zα-ωΑ-Ω]{1,3}[A-Za-z0-9]{0,3})\s+\S")


# --------------------------------------------------------------------------- blocks
def detect_blocks(page: "pymupdf.Page", lines: list[Line], state: LayoutState,
                  tables: list[TableGrid] | None = None) -> list[Block]:
    height, width = page.rect.height, page.rect.width
    tables = page_tables(page) if tables is None else tables
    # visual reading order (ISO pages are single-column): some processed PDFs store "3 Terms ..." before
    # "1 Scope" in the content stream. The stored page text keeps the stream order.
    lines = sorted([ln for ln in lines if not ln.absorbed],
                   key=lambda l_: (not l_.horizontal, round(l_.yc / 3), l_.bbox[0]))
    # rotated text is content (landscape tables set on portrait pages) unless it is a known watermark
    rotated = [ln for ln in lines if not ln.horizontal and not _is_furniture(ln, height)]
    for ln in lines:
        if not ln.horizontal or _is_furniture(ln, height, state):
            if ln.horizontal:
                state.stats["repeated_furniture_lines"] += 1
            ln.used = True
    _merge_baseline_numbers(lines, [t.bbox for t in tables])
    state.in_key = False  # a figure key never continues on the next page
    live = [ln for ln in lines if not ln.used]
    toc_page = sum(1 for ln in live if TOC_LEADER.search(ln.text)) >= 3  # contents pages never hold headings

    # tables: the finder's cell grid filled with text lines inside the box (rotated watermark glyphs are
    # already dropped). Fraction bars look like ruling lines to the table finder: a box level with a
    # right-margin equation number, or an uncaptioned box whose cells hold "=", is a formula, not a table.
    eq_lines = [ln for ln in live if EQ_NUM.match(ln.text) and ln.bbox[0] > 0.6 * width]
    table_at: dict[int, Block] = {}
    for grid in tables:
        box = grid.bbox
        members = [ln for ln in live if not ln.used and _inside(ln, box)]
        if len(members) < 2 or any(box[1] - 6 <= eq.yc <= box[3] + 6 for eq in eq_lines):
            continue
        caps = [ln for ln in live if not ln.used and (TABLE_CAP.match(ln.text) or TABLE_CONT.match(ln.text))
                and ln.bbox[3] <= box[1] + 4 and box[1] - ln.bbox[3] < 80]
        if not caps and any(ln.text.strip() in ("=", "+", "−", "-") for ln in members):
            continue
        block = _table_block(grid, members, max(caps, key=lambda l_: l_.bbox[3]) if caps else None, live, state)
        first = min(members + [ln for ln in live if ln.used and ln in caps], key=lambda l_: lines.index(l_))
        table_at[lines.index(first)] = block

    # equations: glyphs left of a right-margin equation number, inside the band that the neighbouring
    # prose lines and equation numbers leave free
    formula_at: dict[int, Block] = {}
    eqs = sorted([ln for ln in live if not ln.used and EQ_NUM.match(ln.text) and ln.bbox[0] > 0.6 * width],
                 key=lambda l_: l_.vc)
    drawings = None
    for i, eq in enumerate(eqs):
        lo, hi = eq.vc - EQ_WINDOW, eq.vc + EQ_WINDOW
        if i > 0:
            lo = max(lo, (eqs[i - 1].vc + eq.vc) / 2)
        if i + 1 < len(eqs):
            hi = min(hi, (eqs[i + 1].vc + eq.vc) / 2)
        free_lo, free_hi = lo == eq.vc - EQ_WINDOW, hi == eq.vc + EQ_WINDOW
        for ln in live:
            if ln is eq or ln.used or abs(ln.vc - eq.vc) < 4 or not (_is_prose(ln.text) or _is_structural(ln)
                                                                     or _is_text_label(ln)):
                continue
            if ln.vc < eq.vc and ln.vbottom > lo:
                lo, free_lo = max(lo, ln.vbottom - 0.5), False
            elif ln.vc > eq.vc and ln.vtop < hi:
                hi, free_hi = min(hi, ln.vtop + 0.5), False
        band = [ln for ln in live if not ln.used and ln is not eq and ln.bbox[2] <= eq.bbox[0] + 2
                and lo <= ln.vc <= hi and not _is_prose(ln.text) and not _is_structural(ln)
                and not _is_text_label(ln) and not EQ_NUM.match(ln.text)]
        eq.used = True
        for ln in band:
            ln.used = True
        num = EQ_NUM.match(eq.text).group(1)
        if drawings is None:
            try:
                drawings = page.get_drawings()
            except Exception:  # pragma: no cover
                drawings = []
        # glyph boxes from baseline and size (line boxes of some PDFs are several lines tall)
        glyphs = [F.Glyph(sg.text, (sg.bbox[0], sg.baseline - 0.78 * sg.size, sg.bbox[2], sg.baseline + 0.22 * sg.size),
                          sg.size, sg.baseline, sg.font) for ln in band for sg in ln.segs]
        region = (min((ln.bbox[0] for ln in band), default=eq.bbox[0]) - 3, lo, eq.bbox[0], hi)
        raw = " ".join(ln.text for ln in band)
        # an equation taller than the window: glyphs continue right beyond an unbounded edge
        x_lo = region[0]
        cut = [ln for ln in live if not ln.used and ln.bbox[2] <= eq.bbox[0] + 2 and ln.bbox[2] > x_lo
               and not _is_prose(ln.text) and not _is_text_label(ln) and not _is_structural(ln)
               and ((free_lo and lo - 14 <= ln.vc < lo) or (free_hi and hi < ln.vc <= hi + 14))]
        res = F.reconstruct(glyphs, F.primitives(drawings, region), num, raw=raw,
                            extra_reasons=["region_truncated"] if cut else None)
        state.stats["formulas"] += 1
        text = res.plain if res.status != "needs_review" else linearize(band)
        if res.status == "needs_review":
            state.stats["formulas_needs_review"] += 1
        first = min(band + [eq], key=lambda l_: lines.index(l_))
        formula_at[lines.index(first)] = Block(
            "formula", f"{text} ({num})".strip(), label=eq.text, source="pymupdf:formula", data=res.as_dict(),
            bbox=region, confidence=res.confidence)

    # "where" legends of the equations
    legend_at: dict[int, Block] = {}
    for w in [ln for ln in live if not ln.used and (WHERE.match(ln.text) or WHERE_INLINE.match(ln.text))]:
        if WHERE_INLINE.match(w.text):
            var = parse_variable(w.text[5:].strip())
            taken, variables = [], [var] if var else []
        else:
            taken, variables = _legend(w, live)
        if not variables:
            continue
        w.used = True
        for ln in taken:
            ln.used = True
        body = "\n".join([w.text] + [" ".join(x.text for x in row) for row in _visual_rows(taken)])
        legend_at[lines.index(w)] = Block("legend", normalize_hyphens(body), source="pymupdf:legend",
                                          data={"variables": variables})
        state.stats["legends"] += 1

    blocks: list[Block] = []
    para: list[str] = []
    para_clause: str | None = None
    para_kind = "text"
    key_lines: list[str] = []

    def flush() -> None:
        nonlocal para, para_clause, para_kind
        if para:
            blocks.append(Block(para_kind, normalize_hyphens("\n".join(para)), clause=para_clause, source="pymupdf"))
        para, para_clause, para_kind = [], None, "text"

    def flush_key() -> None:
        nonlocal key_lines
        if key_lines:
            blocks.append(Block("figure_key", "\n".join(key_lines), source="pymupdf"))
        key_lines = []

    for idx, ln in enumerate(lines):
        if idx in table_at:
            flush()
            blocks.append(table_at[idx])
        if idx in formula_at:
            flush()
            blocks.append(formula_at[idx])
        if idx in legend_at:
            flush()
            blocks.append(legend_at[idx])
        if ln.used:
            continue
        t = ln.text
        if TOC_LEADER.search(t):  # table of contents entry: text, never a clause
            para.append(t)
            continue
        if t == "Key":
            flush()
            state.in_key = True
            key_lines = [t]
            continue
        if FIG_CAP.match(t):
            state.in_key = False
            flush()
            flush_key()
            blocks.append(_figure_block(t, blocks))
            state.stats["figures"] += 1
            continue
        if state.in_key and key_lines:
            if _KEY_ITEM.match(t) and len(t) < 160 or not _is_prose(t) and len(t) < 60:
                key_lines.append(t)
                continue
            flush_key()  # explanatory prose after the key ends it (the caption may still follow)
            state.in_key = False
        if TABLE_CAP.match(t) or TABLE_CONT.match(t):
            flush()
            m = TABLE_CAP.match(t) or TABLE_CONT.match(t)
            blocks.append(Block("caption", t, label=f"Table {m.group(1)}", source="pymupdf"))
            continue
        heading = None if toc_page and t.lower().rstrip(".") != "contents" else _heading(t, ln, lines, idx, state)
        if heading is not None:
            flush()
            flush_key()
            blocks.append(heading)
            continue
        m = CLAUSE_LINE.match(t)
        if m and not state.in_key and "." in m.group(1) and plausible_next(state.clause_key, clause_key(m.group(1))):
            flush()  # numbered sub-clause with running text: "5.1 The characteristics ..."
            state.clause_key = clause_key(m.group(1))
            para, para_clause = [t], m.group(1)
            continue
        if NOTE.match(t) or EXAMPLE.match(t) or LIST_ITEM.match(t):
            flush()
            para_kind = "note" if NOTE.match(t) else ("example" if EXAMPLE.match(t) else "list")
        para.append(t)
    flush()
    flush_key()
    if rotated:
        blocks.append(Block("text", normalize_hyphens("\n".join(ln.text for ln in rotated)), source="pymupdf:rotated"))
    return blocks


def _figure_block(caption: str, blocks: list[Block]) -> Block:
    """A figure caption; the key directly before it (no heading in between) becomes part of the figure."""
    m = FIG_CAP.match(caption)
    key: list[str] = []
    for i in range(len(blocks) - 1, max(-1, len(blocks) - 4), -1):
        if blocks[i].kind == "heading":
            break
        if blocks[i].kind == "figure_key":
            key = blocks.pop(i).text.split("\n")[1:]
            break
    text = caption if not key else caption + "\nKey\n" + "\n".join(key)
    return Block("figure", text, label=f"Figure {m.group(1)}", source="pymupdf",
                 data={"number": m.group(1), "caption": caption, "key": key})


def _table_block(grid: TableGrid, members: list[Line], cap_line: Line | None, live: list[Line],
                 state: LayoutState) -> Block:
    box = grid.bbox
    if cap_line is not None:
        cap_line.used = True
    for ln in members:
        ln.used = True
    caption = cap_line.text if cap_line else None
    m = (TABLE_CAP.match(caption) or TABLE_CONT.match(caption)) if caption else None
    number = m.group(1) if m else None
    continued = bool(caption and TABLE_CONT.match(caption))
    # unit notes ("Deviations in micrometres") between the caption and the grid
    unit_notes = [ln for ln in live if not ln.used and UNIT_NOTE.match(ln.text) and box[1] - 40 <= ln.yc <= box[1] + 2]
    for ln in unit_notes:
        ln.used = True
    rows, bold, lost = grid_rows(grid, members) if grid.rows else ([], [], 1.0)
    method = "grid"
    if len(rows) < 2 or lost > 0.2:
        rows, bold, method = rows_from_lines(members), None, "lines"
        state.stats["tables_lines"] += 1
    else:
        state.stats["tables_grid"] += 1
    header = header_row_count(rows, bold)
    columns = column_names(rows, header)
    # footnotes directly under the grid ("a  Values for ...")
    foot = [ln for ln in live if not ln.used and box[3] - 1 <= ln.bbox[1] <= box[3] + 40
            and re.match(r"^[a-h]\s+\S", ln.text) and box[0] - 5 <= ln.bbox[0] <= box[2]]
    for ln in foot:
        ln.used = True
    unit_note = " ".join(ln.text for ln in unit_notes) or None
    units = table_units(([unit_note] if unit_note else []) + [c for r in rows[:header] for c in r])
    text = "\n".join(x for x in (caption, unit_note, render_table(None, rows, header)) if x)
    if foot:
        text += "\n" + "\n".join(ln.text for ln in foot)
    # a header cell holding two column labels ("1 2", "3 4") means the grid merged columns that the PDF
    # separates only by spacing: the cells keep every value, but their column assignment must be checked
    merged_header = any(re.fullmatch(r"\d{1,2}[a-z]?\s+\d{1,2}[a-z]?", c.strip()) for r in rows[:header] for c in r)
    data = {"number": number, "caption": caption, "continued": continued, "header_rows": header,
            "columns": columns, "rows": rows, "units": units, "unit_note": unit_note,
            "footnotes": [ln.text for ln in foot], "method": method, "bbox": [round(v, 1) for v in box],
            "alignment_uncertain": merged_header}
    return Block("table", text, label=f"Table {number}" if number else None, source="pymupdf:table", data=data,
                 bbox=box)


def _take(title_lines: list[Line]) -> list[str]:
    for ln in title_lines:
        ln.used = True
    return [ln.text for ln in title_lines]


def _heading(t: str, ln: Line, lines: list[Line], idx: int, state: LayoutState) -> Block | None:
    m_annex = ANNEX.match(t)
    if m_annex and (ln.bold or len(t) < 60) and state.clause_key:  # annexes follow the body
        key = clause_key(m_annex.group(1))
        if plausible_next(state.clause_key, key) or state.clause_key == key:
            state.clause_key, state.in_key = key, False
            parts = [f"Annex {m_annex.group(1)}", m_annex.group(2).strip()]
            nxt = _next_title_lines(lines, idx, limit=3)
            if nxt and ANNEX_TYPE.match(nxt[0].text):  # "(informative)" precedes the bold annex title
                nxt = nxt[:1] + [x for x in _next_title_lines(lines, lines.index(nxt[0]), limit=2) if x.bold]
            text = " ".join(x for x in parts + _take(nxt) if x)
            return Block("heading", text, clause=f"Annex {m_annex.group(1)}", level=1, source="pymupdf")
    if ln.bold and t == "Scope" and not state.clause_key:
        # clause 1 always opens an ISO document; some text layers omit its number
        state.clause_key = (1,)
        return Block("heading", "1 Scope", clause="1", level=1, source="pymupdf")
    if ln.bold and t.lower().rstrip(".") in UNNUMBERED:
        return Block("heading", t, clause=t if t.lower() == "bibliography" else None, level=1, source="pymupdf")
    if state.in_key:
        return None
    m_num = CLAUSE_NUM.match(t)
    m_line = CLAUSE_LINE.match(t)
    num = m_num.group(1) if m_num else (m_line.group(1) if m_line else None)
    # a bold numbered title line (titles never end with a full stop, running text does)
    strong = bool(ln.bold and m_line and not m_line.group(2).rstrip().endswith("."))
    if num is None or not plausible_next(state.clause_key, clause_key(num), strong=strong):
        return None
    top_level = "." not in num
    if m_line:
        title = m_line.group(2).strip()
        # a heading is a short bold line; running text after a sub-clause number is handled by the caller
        if TOC_LEADER.search(title) or not (ln.bold or (top_level and len(title) < 70 and not title.endswith("."))):
            return None
        if top_level and not ln.bold and _is_prose(title) and title.endswith("."):
            return None
    else:
        nxt = _next_title_lines(lines, idx, limit=1)
        if top_level and not ln.bold and not nxt:
            return None
        if nxt and TOC_LEADER.search(nxt[0].text):
            return None
        title = " ".join(_take(nxt))
    state.clause_key = clause_key(num)
    return Block("heading", f"{num} {title}".strip(), clause=num, level=num.count(".") + 1, source="pymupdf")


def _next_title_lines(lines: list[Line], idx: int, limit: int = 2) -> list[Line]:
    """Bold (or short title-like) lines directly following a heading number (not consumed)."""
    out: list[Line] = []
    for ln in lines[idx + 1:]:
        if ln.used:
            continue
        t = ln.text
        if len(out) >= limit or CLAUSE_NUM.match(t) or CLAUSE_LINE.match(t) or _is_prose(t) and not ln.bold:
            break
        if ln.bold or (len(t) < 80 and not t.endswith(".") and not EQ_NUM.match(t)):
            if not ln.bold and t[:1].islower() and not out:
                # a definition term ("standard basic rack tooth profile") is a title only when bold
                break
            out.append(ln)
            if not ln.bold:
                break
        else:
            break
    return out
